const activities = [
    {
        _id: '1',
        date: '05/04/2022',
        title: 'Book Donated',
        description: 'Donated Copies of the Textbook Business Management in a Nutshell',
        image: require("./images/res/BookDonation.jpg"),
        image1: require("./images/res/BookDonation1.jpg"),
    },
    {
        _id: '2',
        date: '12/04/2022',
        title: 'Gurukul App Launch',
        description: 'NGI Gurukul App Made an Internal Launch',
        image: require("./images/res/gurukul.jpg"),
    },
    {
        _id: '3',
        date: '13/04/2022',
        title: 'Vishnu X Easter Celebration',
        description: 'Celebrated Vishu and Easter at Kapil Nadumuttam with different cultural events and games',
        image: require("./images/res/VishnuEasterCeleb.jpg"),
        image1: require("./images/res/VishnuEasterCeleb1.jpg"),
    },
    {
        _id: '4',
        date: '27/04/2022',
        title: 'Prayaana 2K22',
        description: 'Prayaana, intercollagiate Tech Fest conducted every year by MCA department of NCERC',
        image: require("./images/res/Prayaana.jpg"),
        image1: require("./images/res/Prayaana1.jpg"),
    },
    {
        _id: '5',
        date: '07/06/2022',
        title: 'Yoga Session',
        description: 'Conducted a Yoga sesssion on the behalf of YOGA DAY',
        image: require("./images/res/Yoga.jpg"),
        image1: require("./images/res/Yoga1.jpg"),
    },
    {
        _id: '6',
        date: '17/06/2022',
        title: 'Wonderla Trip',
        description: 'As a refreshment trip team mca visitied wonderla water theme park',
        image: require("./images/res/Wonderla.jpg"),
        image1: require("./images/res/Wonderla1.jpg"),
    },
    {
        _id: '7',
        date: '12/08/2022',
        title: 'Poster Design Competition',
        description: 'On National Librarians Day a poster design competition is held with the topic of "INDEPENDENCE DAY"',
        image: require("./images/res/Poster.jpg"),
        image1: require("./images/res/poster1.jpg"),
    },
    {
        _id: '8',
        date: '03/09/2022',
        title: 'Onam Celebrations',
        description: 'Team MCA got First prize in Pookalam Competition',
        image: require("./images/res/Onam.jpg"),
        image1: require("./images/res/Onam1.jpg"),
    },
    {
        _id: '9',
        date: '19/09/2022',
        title: 'Volleyball Inaugration',
        description: 'A Volleyball is bought by Team MCA and inaugrated on the behalf of Head of the MCA Department Dr.Sudheer Maarar',
        image: require("./images/res/Volleyball.jpg"),
        image1: require("./images/res/Volleyball1.jpg"),
    },
    {
        _id: '10',
        date: '22/09/2022',
        title: 'Sharing Day',
        description: 'Students prepared food items & Snacks and distributed among themselves on Sharing Day',
        image: require("./images/res/Sharingday.jpg"),
        image1: require("./images/res/Sharingday1.jpg"),
    },
    {
        _id: '11',
        date: '14/10/2022',
        title: 'Rank Holders',
        description: 'Raseena and Praveena from Team MCA achieved top ranks from the APJ Abdul Kalam Technological University',
        //image: require("./images/sample.jpg"),
    },
    {
        _id: '12',
        date: '25/10/2022',
        title: 'Deepavali Celebrations',
        description: 'Celebrated Deepavali by distributing snacks, bursting crackers and other cultural events',
        //image: require("./images/sample.jpg"),
    }
    ,
    {
        _id: '13',
        date: '05/11/2022',
        title: 'NeCTAR',
        description: 'NeCTAR Coference conducted by Team MCA on "Technologies Annexing Reality" by Prof.Dr.JKM Nair',
        image: require("./images/res/nectar.jpg"),
    }
    ,
    {
        _id: '14',
        date: '11/11/2022',
        title: 'Snehamrutham ',
        description: 'SNEHAMRUTHAM a Team MCA initiative to distribute food every week for the people in need',
        image: require("./images/res/snehamrutham.jpg"),
        image1: require("./images/res/snehamrutham1.jpg"),
    }
    ,
    {
        _id: '15',
        date: '18/11/2022',
        title: 'Debate Competition',
        description: 'MCA Association of NCERC conducted a Debate competition on various topics',
        image: require("./images/res/Debate.jpg"),
        image1: require("./images/res/Debate1.jpg"),
    },
    {
        _id: '16',
        date: '25/11/2022',
        title: 'MCA Association Inaugration',
        description: 'Inaugration of MCA Association',
        image: require("./images/res/Asso.jpg"),
        image1: require("./images/res/Asso1.jpg"),
    },
    {
        _id: '17',
        date: '25/11/2022',
        title: 'Shootout Competition',
        description: 'A Shootout Competition is conducted by Team MCA based on the theme Fifa Worldcup',
        image: require("./images/res/Shootout.jpg"),
        image1: require("./images/res/Shootout1.jpg"),
    },
    {
        _id: '18',
        date: '20/12/2022',
        title: 'Christmas Celebration at Ammaveedu',
        description: 'Team MCA celebrated christmas and spend a day at AMMAVEEDU',
        image: require("./images/res/Christmas2.jpg"),
        image1: require("./images/res/Christmas1.jpg"),
    },
    {
        _id: '19',
        date: '23/01/2022',
        title: 'Industrial Visit',
        description: 'Industrial Visit of Second Years Team MCA',
        image: require("./images/res/iv.jpg"),
        image1: require("./images/res/iv1.jpg"),
    }
            
]

export default activities